### PR TITLE
Added comments in some notebooks

### PR DESCRIPTION
**Pull request by misialq**
As I was looking through some of the notebooks here, I thought I may as well commit some of the comments I added in few of them. 98% of the changes are just new markdown cells with some comments making the notebooks a bit more readable. In the case of the random forest notebook, I added an extended intro cell pointing out which things should have been run before using it and what data is required (as it took me a while to understand it myself) - I hope the steps are correct 😅 

Here is a summary of the changes (as jupyter diffs are a pain to look at...):
- `eval-empo-3-error-rate.ipynb`, `paycheck-eval-empo-3-tpr.ipynb` - added few markdown comments, removed all plots from the second half of both notebooks (since they cannot be generated with the code included there anyway - I guess they were a copy-paste leftover)
- `paycheck-eval-RandomForest.ipynb` - added some comments, mostly an extended intro one describing the steps to be done before executing the notebook
- `paycheck-eval-empo-3.ipynb` - added some markdown comments, fixed a pandas Series/DataFrame error within `_eval_for_class_weights` function, added a column name to the empty DataFrame in in the evaluation part

Hope any of that helps!

### CODE REVIEW

**Comment by misialq** [comment]
On top of the changes described before, I added some new notebooks for the analysis of RF, CNN and Perfect Classifier results, as well as resource usage visualisation one.

**Review by BenKaehler — APPROVED** [review]
Looks good, thanks @misialq. Certainly written to the same standard or better than earlier notebooks :)

**Comment by misialq** [comment]
Thanks @BenKaehler. Unfortunately, it seems that during merge conflict resolution some things got messed up a bit so I'll still need to fix that before merging. Will let you know when done.

**Comment by misialq** [comment]
Alright, should be fixed now. 🚀

**Comment by misialq** [comment]
Hey @BenKaehler! I just realized that this never got merged... Do you think you could do that (I have no write access...)? Thanks! 🙏

**Comment by BenKaehler** [comment]
Merged! Thanks @misialq

**Pull request merged**
